version: '3.3'
services:
  backend:
    container_name: threat-service
    build:
      context: .
    ports:
      - '8081:8081'
    networks:
      - shared_network
    environment:
      SPRING_DATASOURCE_URL: "jdbc:h2:mem:threat-db"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
networks:
  shared_network:
    external: true