-- Kenya (countryId 1) counties: Makueni, Kwale, Mombasa, Mandera
INSERT INTO broadcast_county (id, broadcast_id, countyId, countyName)
VALUES (nextval('broadcast_county_id_seq'), 1, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 1, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 7, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 7, 4, 'Mandera'),
       (nextval('broadcast_county_id_seq'), 13, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 13, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 19, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 19, 4, 'Mandera'),
       (nextval('broadcast_county_id_seq'), 25, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 25, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 31, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 31, 4, 'Mandera'),
       (nextval('broadcast_county_id_seq'), 37, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 37, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 43, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 43, 4, 'Mandera'),
       (nextval('broadcast_county_id_seq'), 49, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 49, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 55, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 55, 4, 'Mandera'),
       (nextval('broadcast_county_id_seq'), 61, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 61, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 67, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 67, 4, 'Mandera'),
       (nextval('broadcast_county_id_seq'), 73, 1, 'Makueni'),
       (nextval('broadcast_county_id_seq'), 73, 3, 'Mombasa'),
       (nextval('broadcast_county_id_seq'), 79, 2, 'Kwale'),
       (nextval('broadcast_county_id_seq'), 79, 4, 'Mandera'),
-- Ethiopia (countryId 6) county: Oromia (only one county)
       (nextval('broadcast_county_id_seq'), 2, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 8, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 14, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 20, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 26, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 32, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 38, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 44, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 50, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 56, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 62, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 68, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 74, 6, 'Oromia'),
       (nextval('broadcast_county_id_seq'), 80, 6, 'Oromia'),
-- Somalia (countryId 2) county: Puntland (only one county)
       (nextval('broadcast_county_id_seq'), 3, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 9, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 15, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 21, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 27, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 33, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 39, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 45, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 51, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 57, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 63, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 69, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 75, 5, 'Puntland'),
       (nextval('broadcast_county_id_seq'), 4, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 10, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 16, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 22, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 28, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 34, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 40, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 46, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 52, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 58, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 64, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 70, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 76, 3, 'Bamunanika'),
       (nextval('broadcast_county_id_seq'), 5, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 11, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 17, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 23, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 29, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 35, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 41, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 47, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 53, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 59, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 65, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 71, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 77, 8, 'Akobo'),
       (nextval('broadcast_county_id_seq'), 6, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 12, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 18, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 24, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 30, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 36, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 42, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 48, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 54, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 60, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 66, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 72, 7, 'Ali Sabieh'),
       (nextval('broadcast_county_id_seq'), 78, 7, 'Ali Sabieh');